export const LINK_APIS = process.env.REACT_APP_API_KEY
export const TEST = 'TEST'
export const TEST2 = 'TEST2'

export const LOADING = 'LOADING'
export const LOADING_COUNTER = 'LOADING_COUNTER'
export const RESET_MSG = 'RESET_MSG'
export const ALERT_SUCCESS_MESSAGE = 'ALERT_SUCCESS_MESSAGE'
export const ALERT_ERROR_MESSAGES = 'ALERT_ERROR_MESSAGES'
export const SUCCESS_MESSAGE = 'SUCCESS_MESSAGE'
export const ERROR_MESSAGES = 'ERROR_MESSAGES'
export const LANGUAGE = 'LANGUAGE'
// export const ERROR_MESSAGES_BACK_END = 'ERROR_MESSAGES_BACK_END'
// SELECT
export const SELECT = 'SELECT'
export const UNSELECT = 'UNSELECT'
export const SELECT_ALL = 'SELECT_ALL'
export const UNSELECT_ALL = 'UNSELECT_ALL'
export const SELECT_ROW = 'SELECT_ROW'
// USER INFO
export const USER_INFO = 'USER_INFO'
// MEMBERS
export const GET_ALL_MEMBERS = 'GET_ALL_MEMBERS'
export const GET_MEMBER_BY_ID = 'GET_MEMBER_BY_ID'
export const GET_ALL_FILTERS_GROUPING = 'GET_ALL_FILTERS_GROUPING'
export const GET_FILTERS_GROUP_BY_ID = 'GET_FILTERS_GROUP_BY_ID'
// Config
export const GET_CONFIG_ITEMS = 'GET_CONFIG_ITEMS'
export const GET_CITIES = 'GET_CITIES'
export const GET_ALL_CONFIG = 'GET_ALL_CONFIG'
// specialist
export const GET_ALL_SPECIALIST = 'GET_ALL_SPECIALIST'
export const GET_SPECIALIST_BY_ID = 'GET_SPECIALIST_BY_ID'
// LeadManagement
export const GET_ALL_LEAD_MANAGEMENT = 'GET_ALL_LEAD_MANAGEMENT'
export const GET_LEAD_MANAGEMENT_BY_ID = 'GET_LEAD_MANAGEMENT_BY_ID'
// Lost and found
export const GET_ALL_LOST_AND_FOUND = 'GET_ALL_LOST_AND_FOUND'
export const GET_LOST_AND_FOUND_BY_ID = 'GET_LOST_AND_FOUND_BY_ID'
